import { defineCollection, z } from "astro:content";
import { file } from "astro/loaders";

/**
 * All book-derived content is typed data loaded from a handful of YAML files.
 *
 * Why YAML files rather than 231 markdown files (docs/decisions.md D20): the printed
 * book is the source of truth and "no invented content" is a hard rule, so a reviewer
 * being able to read one file top to bottom against the printed page is a
 * content-integrity control, not merely a build optimisation. It also means one Zod
 * pass per collection instead of hundreds.
 *
 * These files are generated by tools/extract_book_content.py. Never hand-edit them.
 */

/**
 * Race-control flag. Green = go. Yellow = check in first. Red = adult must be involved.
 *
 * Note there is deliberately no Zod schema here and no `flag` field on any collection
 * below: the printed book assigns no flag to a build, so nothing in these YAML files can
 * carry one without inventing content. Flags are applied by the site in
 * src/lib/build-meta.ts by running the book's own page-61 definition over each build, and
 * that file is the place to audit them. This type only keeps the three names in one spot.
 */
const FLAGS = ["green", "yellow", "red"] as const;

const playStep = z.object({
  n: z.number().int().min(1).max(9),
  title: z.string(),
  text: z.string().min(1),
});

const chapters = defineCollection({
  loader: file("src/content/data/chapters.yaml"),
  schema: z.object({
    n: z.number().int().min(1).max(15),
    slug: z.string(),
    title: z.string(),
    eyebrow: z.string(),
    subtitle: z.string(),
    hillPrinciple: z.string(),
    printedPage: z.number().int(),
    hillIdea: z.object({ term: z.string(), text: z.string().min(1) }),
    /** Book-only. Held here for a short teaser and a page reference, never published whole (D4). */
    story: z.array(z.string()),
    hillRemix: z.string().min(1),
    whatItMeansNow: z.string().min(1),
    play: z.array(playStep).length(5),
    build: z.string().min(1),
    realityCheck: z.string().min(1),
    debrief: z.array(z.string()).length(3),
  }),
});

const builds = defineCollection({
  loader: file("src/content/data/builds.yaml"),
  schema: z.object({
    n: z.number().int().min(1).max(19),
    source: z.string(),
    chapter: z.number().int().min(1).max(15).optional(),
    printedPage: z.number().int(),
    build: z.string().min(1),
    realityCheck: z.string(),
  }),
});

const realityChecks = defineCollection({
  loader: file("src/content/data/reality-checks.yaml"),
  schema: z.object({
    /** Null for the three that belong to no build: the publishing note, the Starting
     *  Point worksheet and the Seven Safe First Offers table. */
    build: z.number().int().nullable(),
    belongsTo: z.string().optional(),
    printedPage: z.number().int(),
    text: z.string().min(1),
  }),
});

const worksheets = defineCollection({
  loader: file("src/content/data/worksheets.yaml"),
  schema: z.object({
    title: z.string(),
    subtitle: z.string(),
    printedPage: z.number().int(),
    fields: z
      .array(
        z.object({
          id: z.string(),
          label: z.string(),
          hint: z.string(),
        }),
      )
      .min(1),
  }),
});

const sequences = defineCollection({
  loader: file("src/content/data/sequences.yaml"),
  schema: z.object({
    title: z.string(),
    subtitle: z.string(),
    printedPage: z.number().int(),
    groups: z
      .array(
        z.object({
          id: z.string(),
          heading: z.string(),
          items: z.array(z.string()).min(1),
        }),
      )
      .min(1),
  }),
});

const offers = defineCollection({
  loader: file("src/content/data/offers.yaml"),
  schema: z.object({
    n: z.number().int().min(1).max(7),
    offer: z.string(),
    deliverable: z.string().min(1),
    firstProof: z.string().min(1),
  }),
});

/**
 * The three passages where the book stops teaching and somebody speaks: Ryan's note on
 * printed page 3, the Afterword on 62, and the author page on 63.
 *
 * These were absent from the site entirely for its whole first build, because every other
 * collection here is a *trackable item* and none of these three carries a 24-Hour Build, so
 * the extractor never reached them. Nothing failed; the site simply had no author in it, and
 * a careful reader ended up crediting a sentence the site had written to Ryan. The extractor
 * now asserts five exact sentences from these pages and exits non-zero if any of them stops
 * coming out of the PDF.
 */
const voice = defineCollection({
  loader: file("src/content/data/voice.yaml"),
  schema: z.object({
    title: z.string(),
    printedPage: z.number().int(),
    /**
     * Who is speaking, which decides how a page may attribute the words.
     * `first`  — Ryan writing as "I". Quotable as his own words.
     * `second` — Ryan writing to the reader as "you". His writing, but never quote it as "I".
     * `third`  — the author page, written *about* him. Never present this as something he said.
     */
    person: z.enum(["first", "second", "third"]),
    /** The one line set above body size under the heading. */
    standfirst: z.string().min(1),
    paragraphs: z.array(z.string().min(1)).min(1),
    /** The Afterword's display line under the build box. Null on the other two. */
    closingLine: z.string().nullable(),
    /** "- Ryan". Only the note is signed. */
    signoff: z.string().nullable(),
  }),
});

export const collections = {
  chapters,
  builds,
  realityChecks,
  worksheets,
  sequences,
  offers,
  voice,
};

/* Derived from FLAGS rather than z.infer: astro:content re-exports `z` as a value only,
   so `z.infer<...>` cannot resolve as a type namespace. Same single source, no drift. */
export type Flag = (typeof FLAGS)[number];
