/**
 * The editorial layer around the 19 Reality Checks.
 *
 * The Reality Check text itself is NOT here. It lives in
 * src/content/data/reality-checks.yaml, extracted verbatim from the printed book, and it
 * is the only thing on these pages quoted as the book's words. Everything in this file is
 * site-authored: a question-shaped H1, a 40–60 word direct answer, why the situation
 * happens, what to do instead, and who to raise it with.
 *
 * Why a separate module rather than the content collection (D20 + content integrity):
 * `reality-checks.yaml` is generated by tools/extract_book_content.py and re-generated on
 * every run, so anything hand-written in it would be silently destroyed. Keeping the two
 * apart also keeps the boundary visible to a reviewer — one file is the book, one file is
 * us — which is the whole point of the "no invented book content" rule.
 *
 * Underscore-prefixed so Astro does not route it. Imported by index.astro and [id].astro.
 *
 * Constraints these strings are written under:
 *  - The answer paragraph is 40–60 words and answers the question in its first sentence
 *    (D30). It is the only text most readers will see, and it is what a search result or
 *    an AI answer will quote.
 *  - No statistic appears anywhere without a primary source, so none appears at all.
 *  - No income figure, no urgency, no promise about outcomes.
 *  - "One adult" is never assumed to be a parent (D25).
 */

/* Mirrors the `flag` enum in src/content.config.ts and the FlagLevel type in
   components/Flag.astro. Declared rather than imported: content.config.ts currently fails
   to type-check its own `Flag` export (see this team's report), and a safety page should
   not inherit that. There is no fourth level, here or anywhere. */
type FlagLevel = "green" | "yellow" | "red";

export type ThemeId =
  | "money-and-contracts"
  | "privacy-and-data"
  | "online-contact"
  | "mental-health"
  | "platform-rules"
  | "scams-and-urgency";

export interface Theme {
  id: ThemeId;
  title: string;
  /** One line, on the library page, saying what this group of risks has in common. */
  blurb: string;
}

export interface CheckMeta {
  /** Matches the id in src/content/data/reality-checks.yaml. */
  id: string;
  theme: ThemeId;
  /** The H1. Question-shaped, because that is how it will be asked. */
  question: string;
  /** Short form for the library index and for prev/next. */
  short: string;
  /** 40–60 words, direct answer in sentence one. */
  answer: string;
  /** What makes this situation normal enough that it catches people. */
  why: string[];
  /** The safe route, in the book's register: concrete, small, doable today. */
  instead: string[];
  /** First port of call for this specific check. The general list is on every page. */
  talkTo: string[];
  /** Race control (D12). Green = go. Yellow = check in first. Red = an adult is required. */
  flag: FlagLevel;
  /** For the three that guard no build: where the check actually lives on the site. */
  standalone?: { href: string; label: string };
}

export const THEMES: Theme[] = [
  {
    id: "money-and-contracts",
    title: "Money and contracts",
    blurb: "The moment a project takes payment, it takes obligations with it.",
  },
  {
    id: "privacy-and-data",
    title: "Privacy and what you give away",
    blurb: "Detail you publish once cannot be un-published, and it is rarely required.",
  },
  {
    id: "online-contact",
    title: "Online contact",
    blurb: "People you have only met online, and what they are allowed to ask for.",
  },
  {
    id: "mental-health",
    title: "Mental health and burnout",
    blurb: "When the problem stopped being motivation and became sleep, eating, school or how you feel.",
  },
  {
    id: "platform-rules",
    title: "Platform rules and your age",
    blurb: "Age rules are boring, real, and different in every country and every app.",
  },
  {
    id: "scams-and-urgency",
    title: "Scams and urgency",
    blurb: "Anything built to stop you checking is telling you to check.",
  },
];

/** The order the library renders in, and the order prev/next follows. */
export const THEME_ORDER: ThemeId[] = THEMES.map((t) => t.id);

export const CHECKS: CheckMeta[] = [
  /* --- Money and contracts ------------------------------------------------- */
  {
    id: "publishing-note",
    theme: "money-and-contracts",
    question: "What has to be checked before you sell something you made?",
    short: "Before you sell what you made",
    answer:
      "Before anything you made goes on sale, someone qualified should check the title, any trademark wording, the legal notices, the links, the privacy terms, any contest, and the payment flow — in each country you sell in. This book prints that rule about itself on page 2, which is the standard it is asking you to hold it to.",
    why: [
      "Naming, payment handling and privacy wording are decided by law in the country of sale, not by the person selling. They are also the parts nobody enjoys, so they are the parts that get left until after launch.",
      "The person who made the thing is the last person likely to spot the problem in it. That is not a failing; it is what being close to your own work does.",
    ],
    instead: [
      "Publish it free, or show it to a small number of people, while it is still unchecked. Nothing on this site is behind a price, for the same reason.",
      "Before money is involved, write the list out: title, trademark wording, legal notices, links, privacy terms, contests, payment flow. Hand the list to an adult rather than a summary of it.",
    ],
    talkTo: [
      "A parent or guardian first, for anything that will be sold.",
      "For a real commercial release, a publishing or legal professional in the country you are selling in. This is one of the few places on this site where an amateur answer is not good enough.",
    ],
    flag: "red",
    standalone: { href: "/terms", label: "Terms and legal notices" },
  },
  {
    id: "game-plan",
    theme: "money-and-contracts",
    question: "What has to involve an adult once a project starts making money?",
    short: "When a plan starts making money",
    answer:
      "Paid projects, products, customer data, shipping, taxes and contracts. All six change what a plan is, and the rules for each depend on where you live and how old you are. Work with a parent or guardian from the first paid step. A smart plan contains legal and safety checks, not only growth tasks.",
    why: [
      "Planning tools are built to make work feel fast, and the tasks that involve an adult are the slow ones. It is easy to write a twelve-week plan in which every single step is something you can do alone, and then discover that the step which actually earns anything is not.",
      "Customer data is the one people miss. A spreadsheet of names, addresses and orders is other people's personal information, and holding it is a responsibility whatever age you are.",
    ],
    instead: [
      "Write the twelve-week outcome and the first three milestones, then mark every milestone that crosses into money, personal data, shipping or a contract.",
      "Attach an adult to those marked milestones before they start, not when they go wrong.",
    ],
    talkTo: [
      "A parent or guardian, before the first paid step rather than after it.",
      "For tax, registration or invoicing, a qualified local professional — the rules are country-specific and guessing is expensive.",
    ],
    flag: "red",
  },
  {
    id: "money-mindset",
    theme: "money-and-contracts",
    question: "Is this book financial advice?",
    short: "Is this financial advice?",
    answer:
      "No. It is educational. Under-18 accounts, taxes, investing, online payments and the rules for paid work all vary by country, and none of them are guessable from a video. Use a parent or guardian and qualified local guidance. Never borrow money to build something, and never invest money you cannot afford to lose.",
    why: [
      "Almost all money content online is written for adults, in one country, under rules that may not be the ones you live under. It rarely says so.",
      "Under-18 rules are the part that gets skipped, because they make the advice apply to fewer people.",
    ],
    instead: [
      "Look at your last ten purchases and sort each into Spend, Save or Build. It costs nothing, needs no account, and it is the only part of this that is genuinely yours to do alone.",
      "Pick one 90-day target and work out the weekly amount. A number you can name beats a feeling about money.",
    ],
    talkTo: [
      "A parent or guardian, for anything involving an account, a payment or a purchase.",
      "A qualified local professional for tax and accounts. Bank websites in your own country are a better starting point than a creator.",
    ],
    flag: "red",
  },
  {
    id: "seven-safe-offers",
    theme: "money-and-contracts",
    question: "What makes a first offer safe?",
    short: "What makes an offer safe",
    answer:
      "Four things: the scope is small, the contact route goes through an adult, it needs no access to anyone's private accounts, and it promises only a result you can control. An offer failing one of the four is not a smaller version of a safe offer. It is a different offer, and it should be rewritten before it is sent.",
    why: [
      "The risky part of first freelance work is almost never the work. It is access — passwords, admin rights, someone's inbox, someone's payment details — and access tends to be requested casually, as a convenience.",
      "Promising a result you do not control is the other half. Traffic, sales and followers depend on things nobody can guarantee, so promising them turns an ordinary job into a dispute.",
    ],
    instead: [
      "Start from the seven offers printed on page 57. Each already has a small scope and a first proof attached.",
      "Write the deliverable and the deadline down. If the sentence needs the word “guarantee” to sound good, the offer is the wrong shape.",
    ],
    talkTo: [
      "The adult who owns the contact route. If nobody owns it yet, that is the first thing to fix, before the offer goes anywhere.",
    ],
    flag: "yellow",
    standalone: { href: "/offers", label: "Seven Safe First Offers" },
  },

  /* --- Privacy and what you give away -------------------------------------- */
  {
    id: "dream-big",
    theme: "privacy-and-data",
    question: "Do you have to post your goal publicly to stick to it?",
    short: "Posting your goal publicly",
    answer:
      "No. Accountability works privately — one safe witness who knows what you promised is enough. Posting a goal in public adds an audience, and an audience adds pressure, exposure and people who now know something about you. When safety, family or anxiety is involved, keep it private. The goal is action, not exposure.",
    why: [
      "Public accountability is sold as a free productivity trick. What it actually adds is an audience, and an audience is not free — it changes what you are willing to try, and it is very hard to take back.",
      "A goal posted publicly also announces something about your life: what you do not have yet, what you are struggling with, sometimes where you are.",
    ],
    instead: [
      "Tell one safe witness the dream and the 30-day proof. That is the whole mechanism.",
      "Put the evidence in the folder as you go. Post the finished result later if you want to — after it exists, when you are choosing to, and on your terms.",
    ],
    talkTo: [
      "Your safe witness — the person named on your Starting Point sheet.",
      "If the reason to keep it private is a person rather than a preference, tell an adult that part too.",
    ],
    flag: "green",
  },
  {
    id: "create-magic",
    theme: "privacy-and-data",
    question: "Can you put someone else's work into an AI tool?",
    short: "Other people's work in an AI tool",
    answer:
      "Not without permission. That covers a friend's photo, a classmate's writing, a private chat, a client's file and anything you did not make. Credit collaborators, respect copyright and the platform's own rules, and never upload private material. A simple test: if you would not show the person the upload, do not make it.",
    why: [
      "An AI tool accepts anything you paste into it, and accepting is not the same as being allowed. The interface gives no signal at all about whose material this is.",
      "Uploading someone's private message or photo also hands it to a company, which is a second thing they did not agree to.",
    ],
    instead: [
      "Build the piece from three ingredients out of your own life. That is the actual assignment, and it is the version nobody can take down.",
      "Ask before you use anyone's work, voice or likeness, and credit them by name when you do.",
    ],
    talkTo: [
      "The person whose work it is. Asking is short and it settles the question.",
      "A teacher for schoolwork, and a parent or guardian for anything involving a client's material.",
    ],
    flag: "yellow",
  },
  {
    id: "vibe-check",
    theme: "privacy-and-data",
    question: "How much of yourself should you post to sound authentic?",
    short: "Authenticity versus privacy",
    answer:
      "Less than the word suggests. Honest does not mean unprotected. Keep your location, your school schedule, private conflicts and anything you are still in the middle of off the feed. Post the work, and the question you actually want answered. A detail cannot be un-posted, and attention does not pay for what giving it away costs.",
    why: [
      "Platforms reward the most exposing version of a post, so the feedback you get pushes in one direction only. Nothing pushes back.",
      "A conflict posted while it is still happening involves someone who did not agree to be posted about, and the version written mid-argument is the one that stays up.",
    ],
    instead: [
      "Choose your three signal words and check the post against them before it goes out.",
      "Share one 30-second idea and ask one clear question. Write down what comes back — that is the part worth having.",
    ],
    talkTo: [
      "Your safe witness, before posting anything that is about another person as well as you.",
    ],
    flag: "yellow",
  },

  /* --- Online contact ------------------------------------------------------ */
  {
    id: "squad-goals",
    theme: "online-contact",
    question: "What should you never share with someone you build with online?",
    short: "Building with people online",
    answer:
      "Your address, your school schedule, private documents, passwords and financial details. None of them are needed to make something together. Use platforms a parent or guardian has approved, keep the work in the shared file and nothing else there, and involve an adult before you meet anyone from online in person.",
    why: [
      "Collaboration is a normal reason to ask for details, which is exactly why it is used as one. A request that would look strange from a stranger looks ordinary from a project partner.",
      "It also arrives gradually. Each single question seems small next to the one before it, and there is no moment that obviously counts as the line.",
    ],
    instead: [
      "Run a 20-minute build call, bring one goal, and end with one task per person. That needs a shared document and nothing else.",
      "Keep a rule you do not renegotiate mid-conversation: no address, no schedule, no passwords, no payment details, ever, for any reason given.",
    ],
    talkTo: [
      "A parent or guardian before any in-person meeting — this one is not optional.",
      "Tell an adult straight away if someone asks you to keep the friendship secret, moves you to a private app, or asks for anything on the list above. Those three are the pattern, not bad manners.",
    ],
    flag: "red",
  },
  {
    id: "mindful-tech",
    theme: "online-contact",
    question: "What do you do about threats, sexual messages or blackmail online?",
    short: "Threats, sexual messages, blackmail",
    /* The one page on this site most likely to be opened by a reader who is frightened
       while they read it. So: the reassurance is in the answer, not buried three bullets
       down; the instructions are short; nothing here says or implies that they made a
       mistake; and the last thing on the list is a named kind of adult. */
    answer:
      "Tell a trusted adult today, and report it in the app. Do not reply, do not pay, and do not delete the evidence. None of this is your fault, including anything you already sent. Handling it alone is what the other person is counting on, and the same is true of harassment.",
    why: [
      "Blackmail works on silence, and it manufactures the silence itself: the threat is always that telling someone would be worse than paying. It is not. Telling someone is the step that starts ending it.",
      "Paying or complying does not stop it either — it confirms that the pressure works.",
      "Adults who work with teenagers — teachers, safeguarding leads, the police — have seen this before and have a routine for it. You will not be the first person they have helped with it.",
    ],
    instead: [
      "If this is about your phone rather than a person, that is the ordinary version and it is what the build is for: turn off non-human notifications for 24 hours and take one 30-minute offline block.",
      "If someone is threatening you, pressuring you for images, or demanding money: screenshot what you have, block the account, and use the platform's own reporting tool. Keep the evidence even though you want it gone.",
      "Then tell one adult the same day — a parent or guardian, a teacher, or your school's safeguarding lead. If the first one does not act, tell a second. That is allowed, and it is not going behind anyone's back.",
    ],
    talkTo: [
      "A parent or guardian, a teacher, or your school's safeguarding lead.",
      "The police, or your local emergency number, if you have been threatened or you are frightened for your safety.",
      "The platform, through its report function, as well as — never instead of — a person.",
    ],
    flag: "red",
  },

  /* --- Mental health and burnout ------------------------------------------- */
  {
    id: "believe-it",
    theme: "mental-health",
    question: "When is low confidence more than a mindset problem?",
    short: "When self-talk is more than mindset",
    answer:
      "When it reaches your sleep, your school, your eating, your relationships or your ordinary day. Self-talk behaving like that is not a motivation gap and it does not answer to a better morning routine. It is worth telling a trusted adult, and worth a qualified professional's time. Early is a much easier conversation than late.",
    why: [
      "Self-help language treats every doubt as a mindset issue you can out-argue, which works for the ordinary kind and quietly fails for the other kind.",
      "The second kind is harder to notice from inside, because it explains itself as an accurate description of you rather than as a symptom.",
    ],
    instead: [
      "Name what it is actually affecting — sleep, eating, school, people — rather than trying to rate how bad it is.",
      "Write one becoming statement and do one small action that proves it. Log what you did, not how impressive it looked. Keep the action small enough to be true.",
    ],
    talkTo: [
      "A parent or guardian, a school counselor, or a family doctor.",
      "A teacher, if the effect is showing up at school first — often it does.",
    ],
    flag: "yellow",
  },
  {
    id: "manifest-it",
    theme: "mental-health",
    question: "Does visualizing the outcome make it happen?",
    short: "Does visualizing work?",
    answer:
      "No. Rehearsing the process — including the mistake and the recovery — can help you prepare. Picturing the finished result does not produce it, and it does not treat anxiety. If pressure is showing up as panic or racing thoughts, that deserves support from a trusted adult or a professional rather than a longer visualization.",
    why: [
      "Imagining the finished thing feels like progress, and it arrives with all the satisfaction of having done it. That is precisely the problem: the feeling is the same, the work is not.",
      "It is also why this site has no vision board and no dream collage. Those were ruled out on the evidence, not on taste.",
    ],
    instead: [
      "Run one 60-second process rehearsal. Put a mistake in it and a recovery from the mistake — that is the part that is worth anything.",
      "Then do ten minutes of the real work it was about, immediately.",
    ],
    talkTo: [
      "A trusted adult, or a professional, when the pressure is physical: panic, racing thoughts, not sleeping before the thing.",
    ],
    flag: "yellow",
  },
  {
    id: "unstoppable",
    theme: "mental-health",
    question: "Is burnout a sign you are working hard enough?",
    short: "Burnout is not proof",
    answer:
      "No. Burnout is not proof of ambition, and exhaustion is not a receipt. If a goal is costing you sleep, health, school or the people around you, the system is wrong rather than you — change the system, and tell a trusted adult. Persistence includes pausing, and it includes choosing a safer path.",
    why: [
      "A great deal of content aimed at teenagers treats rest as the thing separating you from the people who make it. That is an argument for exhaustion, and it is being made to you by people selling something.",
      "Streaks make it worse when they can be broken, because then they run on the fear of losing one. The book's seven-day streak is a count you repair rather than lose, and this site keeps no streak of its own.",
    ],
    instead: [
      "Define the minimum version of your streak — the version you can still do on the worst day of the week — and run that one.",
      "If a day is missed, repair it and continue. Days built is the count. There is nothing to lose and nothing to reset.",
    ],
    talkTo: [
      "A trusted adult, before it costs you the thing you were building it for.",
      "A family doctor if sleep or eating has changed.",
    ],
    flag: "yellow",
  },
  {
    id: "fearless",
    theme: "mental-health",
    question: "When is “just be brave” the wrong advice?",
    short: "When courage talk is a red flag",
    answer:
      "When it is being used to move you toward unsafe contact, substances, a risky stunt, a financial bet, or secrecy from a trusted adult. Courage language is easy to borrow and easy to aim at someone. Fear that arrives as anxiety or panic is real and it is treatable; asking for professional help is strength, not the opposite of it.",
    why: [
      "“Don't be scared” is a genuinely useful sentence about publishing your first piece of work, and a dangerous one about getting into a car. The words are identical, which is what makes them usable by someone with a motive.",
      "If a person is using your own courage against your caution, that is not encouragement. It is pressure wearing encouragement's clothes.",
    ],
    instead: [
      "Write the five-step fear ladder and do step one today. The steps are supposed to be boring at the bottom.",
      "Tell one trusted person what the final step is. That is not only accountability — it is the check on whether the ladder is safe at all.",
    ],
    talkTo: [
      "The trusted person named in your ladder.",
      "A professional if fear is arriving as panic, or if it is stopping ordinary things.",
    ],
    flag: "yellow",
  },
  {
    id: "intuition-flow",
    theme: "mental-health",
    question: "How do you tell intuition from anxiety?",
    short: "Intuition or anxiety?",
    answer:
      "Both arrive in the body, which is why they are confused. Anxiety tends to repeat a broad danger signal about many things at once; intuition is usually quieter and about one specific thing. When the feeling is intense or keeps returning, that is a reason to slow down and get support — not a reason to act faster.",
    why: [
      "“Trust your gut” assumes a calm nervous system underneath. It is advice written by people for whom the signal is rare.",
      "Acting fast on an anxious signal also tends to work, briefly, which teaches you to do it again.",
    ],
    instead: [
      "Write down the one idea or decision that keeps coming back. Specific and repeated is the useful combination.",
      "Design a test that costs under an hour and less than a week's pocket money. If it costs more than that, or it involves other people's money or safety, replace the test with a conversation with an adult.",
    ],
    talkTo: [
      "A trusted adult when the feeling is intense, persistent, or about something you cannot test cheaply.",
    ],
    flag: "yellow",
  },
  {
    id: "real-rich",
    theme: "mental-health",
    question: "Is it your job to fix your family's money?",
    short: "Your family's money is not your job",
    /* A reader whose house is short of money is reading this. The answer names one
       specific adult and makes the ask small, because "talk to someone" without a name
       and without a size is the advice people do not act on. */
    answer:
      "No. Your family's money is not your responsibility, and your worth is not a number you earn. If money at home is frightening, or you are carrying it quietly, that is worth telling someone whose job includes it — a school counselor is a good first stop, and it does not have to be a long conversation.",
    why: [
      "Nobody hands a teenager this job. It gets picked up quietly, from overheard conversations, and it is rarely mentioned to anyone.",
      "It also converts easily into the belief that earning would fix it, which turns an ordinary project into something it cannot carry.",
    ],
    instead: [
      "Score the six areas — Skills, Health, Time, People, Money, Impact — from 1 to 10, honestly.",
      "Take one action for the lowest area. That action is allowed to be “tell someone” — a teacher, a school counselor, a coach — and when the lowest area is Money or Health, it usually is.",
    ],
    talkTo: [
      "An adult outside the situation: a teacher, a school counselor, a coach, or another family member.",
      "A school counselor is a reasonable first stop when the money worry is at home.",
    ],
    flag: "yellow",
  },

  /* --- Platform rules and your age ----------------------------------------- */
  {
    id: "starting-point",
    theme: "platform-rules",
    question: "What rules should you set for yourself before you start?",
    short: "The rule you set before you start",
    answer:
      "Four, and they are the four printed on page 9 for you to sign: do not lie about your age, do not bypass platform rules, do not trade private details for attention, and do not handle risky money, contracts, meetings or travel alone. Everything else on this site assumes you kept them.",
    why: [
      "Every one of those four gets easier to break later, when something is finally going well and stopping feels expensive. That is the moment the rule is for.",
      "Deciding in advance is much cheaper than deciding under pressure, because under pressure the decision is being made by whoever is applying it.",
    ],
    instead: [
      "Write the rule out before the first build, not after the first problem.",
      "Keep it where you will actually see it — the front of the receipts folder is the obvious place.",
    ],
    talkTo: [
      "Your safe witness: a parent, teacher, coach or mentor who knows what you signed.",
    ],
    flag: "yellow",
    standalone: { href: "/worksheet/starting-point", label: "Your Starting Point worksheet" },
  },
  {
    id: "first-offer",
    theme: "platform-rules",
    question: "Can someone under 18 sell work online?",
    short: "Selling work under 18",
    answer:
      "Often yes, and never by pretending otherwise. Contracts, accounts, marketplaces, payment providers, taxes and working hours all carry age rules that differ by country and by platform. Build with a parent or guardian from day one, in their account where the platform requires it. Never lie about your age or route around a platform rule.",
    why: [
      "The rules are dull and the sign-up form is one click, so the fastest path is the one that skips them. It is also the one that loses the account and the money in it.",
      "An age lie is not a small start-up hack either. It voids the arrangement it was used to create, which means it lands at exactly the moment there is finally something to lose.",
    ],
    instead: [
      "Write the one-sentence offer: I help [specific person] get [specific result] by [safe method].",
      "Build or improve one portfolio example today. A portfolio needs no account, no age and nobody's permission.",
      "Set up the payment route in an adult's name from the start, so it never has to be fixed retrospectively.",
    ],
    talkTo: [
      "A parent or guardian, from day one rather than at the first invoice.",
      "The platform's own terms — the age section is short, and it is the actual answer for that platform.",
    ],
    flag: "red",
  },

  /* --- Scams and urgency --------------------------------------------------- */
  {
    id: "level-up",
    theme: "scams-and-urgency",
    question: "Should you buy a course that promises fast income?",
    short: "Courses promising fast income",
    answer:
      "No. Someone promising fast income is selling the promise, because the result is not theirs to give. Start with free or low-cost learning, build one real project, and involve a parent or guardian before any purchase, contract or paid work. If the offer cannot survive one night of sleep, it was never a course.",
    why: [
      "The pitch is always the same shape: a result you cannot verify, sold by someone whose actual income is the sale.",
      "It works because wanting to get good at something is a real feeling, and paying for something is the fastest available action that resembles progress.",
    ],
    instead: [
      "Choose one skill and one 30-day proof project. Spend 25 minutes on the first free tutorial or build session.",
      "Save a screenshot labeled Day 1. That file is worth more than the course, and it is evidence rather than a receipt for hope.",
    ],
    talkTo: [
      "A parent or guardian before any money moves — this includes trials, subscriptions and “free” courses that take a card.",
      "A librarian or a teacher for free material. It is their job and they are good at it.",
    ],
    flag: "red",
  },
  {
    id: "boss-decisions",
    theme: "scams-and-urgency",
    question: "Is an offer that expires tonight ever real?",
    short: "Offers that expire tonight",
    answer:
      "Treat the deadline itself as the warning. Urgency is a common manipulation tactic and it exists to stop you checking. Never send money, sign terms, share ID, meet a stranger or promote a financial product without a parent or guardian and proper advice. A legitimate opportunity survives an adult review and a night of sleep.",
    why: [
      "Everything that makes a decision safe — asking someone, reading it twice, sleeping on it — takes time. Removing time removes all of it at once, which is why urgency is worth more to a scam than any other feature.",
      "It is aimed at teenagers deliberately, because a fast yes is easier to get from someone who has been told that hesitating is what unsuccessful people do.",
    ],
    instead: [
      "Fill the four boxes: Facts, Values, Downside, Reviewer. The Reviewer box is the one that matters here.",
      "Set a decision time within 24 hours if the choice is genuinely low-risk. If it is not, ask an adult first — there is no version of this where the deadline wins.",
    ],
    talkTo: [
      "A parent or guardian before money, ID, terms or a meeting is involved.",
      "Any adult at all, if the pressure is coming from someone you know. Pressure from a friend is still pressure.",
    ],
    flag: "red",
  },
];

const BY_ID = new Map(CHECKS.map((c) => [c.id, c]));

export const metaFor = (id: string): CheckMeta | undefined => BY_ID.get(id);

/** Library order: grouped by theme, in THEME_ORDER, and by printed page within a theme. */
export function orderedIds(printedPage: (id: string) => number): string[] {
  return THEME_ORDER.flatMap((theme) =>
    CHECKS.filter((c) => c.theme === theme)
      .sort((a, b) => printedPage(a.id) - printedPage(b.id))
      .map((c) => c.id),
  );
}

/**
 * Named on every Reality Check page and on the parents page (D25).
 *
 * The safety system's single point of failure is that it delegates the decision to an
 * adult who may be absent, working nights, or unsupportive. Naming only "a parent" ends
 * the path for exactly the readers with the least support, silently.
 */
export const WHO_COUNTS: string[] = [
  "A parent or guardian",
  "A teacher, or a school counselor",
  "A coach or club leader",
  "A librarian",
  "A youth worker",
  "A brother or sister over 18",
];

/**
 * The book's own closing rule, printed on page 61 under "A simple family rule".
 * Both sentences, quoted, never paraphrased — the first one is the operative safety
 * instruction, not decoration, so it must never be dropped when the rule is rendered.
 */
export const FAMILY_RULE =
  "No secrecy around money, meetings, identity documents, or pressure. " +
  "A legitimate opportunity can survive an adult review and a night of sleep.";
